# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit]
default_language_version:
  python: python3.12
exclude: "templates/.*"
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
    exclude: "(.bumpversion.cfg)"
  - id: end-of-file-fixer
    exclude: ".bumpversion.cfg"
  - id: check-added-large-files
  - id: requirements-txt-fixer
- repo: https://github.com/abravalheri/validate-pyproject
  rev: "v0.24.1"
  hooks:
    - id: validate-pyproject
- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.1
  hooks:
  - id: pyupgrade
- repo: https://github.com/PyCQA/bandit
  rev: "1.8.3"
  hooks:
    - id: bandit
      args:
        - "--quiet"
        - "--configfile=pyproject.toml"
      additional_dependencies: [ "bandit[toml]" ]
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version. Keep this in sync with the venv installed version
  rev: v0.11.5
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
