# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Tests

on:
  pull_request:
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v4

      - name: Install pff-tools
        run: |
          sudo apt-get update
          sudo apt-get -y install pff-tools

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependancies
        run: uv sync

      - name: Code quality check
        run: uv run pre-commit --all-files

      - name: Run pytest
        run: uv run pytest
